services:
  game-engine:
    build: ./game-engine
    ports:
      - "8001:8000"
    environment:
      - PYTHONPATH=/app

  web-app:
    build: ./web-app
    ports:
      - "8000:8000"
    volumes:
      - ./web-app:/app
    environment:
      - MONGO_URI=${MONGO_URI}
      - DB_NAME=katydid_brigade
      - GAME_ENGINE_URL=http://game-engine:8000
      - SECRET_KEY=${SECRET_KEY}
      - FLASK_DEBUG=1
    depends_on:
      - game-engine
